internease/base/urls.py
from django.urls import path
from base import views  
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('applied-interns/', views.applied_interns, name='applied_interns'),
    path('success/', views.success_page, name='success'),
    path('', views.apply, name='apply'),
    path('register/', views.register_intern, name='register'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internease/internease/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

internease/base/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.expressions import OrderBy


class InternApplication(models.Model):
    name = models.CharField(max_length=100)
    tel = models.CharField(max_length=20)
    email = models.EmailField(max_length=100)
    school = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    support_leter = models.FileField(upload_to='support_leter')
    photo =  models.FileField(upload_to='photo')
    is_registered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = "Applications"
    
    def __str__(self):
        return self.name + " | " + self.tel

amounts = (('10000frs','10000frs'), ('20000frs', '20000frs'),)

class InternRegistration(models.Model):
    intern_id = models.CharField(primary_key=True, max_length=100)
    name = models.CharField(max_length=100)
    account = models.OneToOneField(InternApplication, on_delete=models.CASCADE, related_name='application')
    momo_number = models.CharField(max_length=20)
    amount = models.CharField(max_length=100, choices=amounts)
    created = models.DateTimeField(auto_now_add=True)
    has_paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = "Registered Interns"
    
    def __str__(self):
        return self.intern_id + "-" + self.name

internease/company/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=100)
    tel = models.CharField(max_length=30)
    email = models.EmailField(max_length=100)
    description = models.TextField(max_length=500)
    photo = models.FileField(upload_to='company_photo/')
    address = models.CharField(max_length=100)
    website = models.URLField(max_length=200)
    location = models.CharField(max_length=1000, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = "Company"
    
    def __str__(self):
        return self.name + " | " + str(self.website) + " | " + str(self.location)

internease/base/forms.py
from django.forms.models import model_to_dict
from base.models import InternApplication, InternRegistration
from django import forms

class InternApplicationForm(forms.ModelForm):
    class Meta:
        model = InternApplication
        exclude = ['created']
        
class InternRegistrationForm(forms.ModelForm):
    class Meta:
        model = InternRegistration
        exclude = ['has_paid', 'created', 'account', '']

internease/base/views.py
from django.shortcuts import redirect, render
from base.forms import InternApplicationForm, InternRegistrationForm
from django.contrib import messages
from base.models import InternApplication
from django.contrib.auth.decorators import login_required


def applied_interns(request):
    interns = InternApplication.objects.filter()
    context = {'interns': interns}
    return render(request, 'base/applied_interns.html', context)

def success_page(request):
    context = {}
    return render(request, 'base/success.html', context)
def apply(request):
    form = InternApplicationForm()
    if request.method == 'POST':
        form = InternApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('base:success')
    context = {'form':form}
    return render(request, 'base/apply.html', context)


def register_intern(request):
    form = InternRegistrationForm()
    if request.method == 'POST':
        form = InternRegistrationForm(request.POST)
        if form.is_valid():
            registered_intern = form.save(commit=False)
            if registered_intern.has_paid:
                register_intern.save()
                return redirect('base:success')
        else:
            messages.error(request, 'Registration Failed, maybe your credentails were not valid')
    context = {'form':form}
    return render(request, 'base/register.html', context)

internease/company/views.py
from django.shortcuts import render,redirect
from company.models import Company
from company.forms import CompanyRegistrationForm
from django.contrib import messages

def company_register(request):
    form = CompanyRegistrationForm()
    if request.method == 'POST':
        form = CompanyRegistrationForm(request.POST)
        if form.is_valid():
            registered_company = form.save(commit=False)
            registered_company.name = registered_company.name.lower()
            registered_company.save()
            return redirect('base:home')
        else:
            messages.error(request, "failed to register, the credetials you provided might contain invalid input")
    context = {'form':form}
    return render(request, 'company/register.html', context)

internease/base/templates/base/applied_interns.html
{% extends "main.html" %}

{% block title %}
    registered interns
{% endblock title %}

{% block content %}
    <div class="interns">
        {% for intern in interns %}
          <div class="intern">
            <div class="info">
                <img src="{{intern.photo.url}}" alt="photo">
                <div>
                    <table  border="">
                        <thead>
                            <tr><th>Name</th><th>Tel</th><th>Email</th><th>School</th><th>Department</th></tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><p>{{intern.name}}</p></td>
                                <td><p>{{intern.tel}}</p></td>
                                <td><p>{{intern.email}}</p></td>
                                <td><p>{{intern.school}}</p></td>
                                <td> <p><small>{{intern.department}}</small></p></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="support_letter">
                <img src="{{intern.support_leter.url}}" alt="support letter">
            </div>
          </div>
        {% endfor %}
    </div>
{% endblock content %}

internease/base/templates/base/apply.html
{% extends "main.html" %}
{% load static %}

{% block title %}
application
{% endblock title %}

{% block content %}
<section class="apply">
    <div>
        <h1>Apply For Internship</h1>
        <p>Provide additional Information below, we will get in touch with you within 24 hours</p>
    </div>
    <div>
        <form action="" class="apply_form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="name">Your Name</label>
                {{form.name}}
            </div>
            <div>
                <label for="tel">Your Tel</label>
                {{form.tel}}
            </div>
            <div>
                <label for="email">Your Email</label>
                {{form.email}}
            </div>
            <div>
                <label for="school">Your school</label>
                {{form.school}}
            </div>
            <div>
                <label for="department">Your Departent</label>
                {{form.department}}
            </div>
            <div>
                <label for="support_leter">upload your internship support Document *.pdf only</label>
                {{form.support_leter}}
            </div>
            <div>
                <label for="photo">Your Photo</label>
                {{form.photo}}
            </div>
            <button type="submit">Apply</button>
        </form>
    </div>
</section>
{% endblock content %}

internease/base/templates/base/register.html
{% extends "main.html" %}
{% load static %}

{% block title %}
    Register
{% endblock title %}

{% block content %}
    <section class="apply">
    <div>
        <h1>Register your Internship</h1>
        <p>Provide additional Information below to be registered</p>
    </div>
    <div>
        <form action="" class="apply_form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
             <div>
                <label for="intern_id">ID recieved via email from CivilSalt</label>
                {{form.intern_id}}
            </div>
            <div>
                <label for="name">Your Name</label>
                {{form.name}}
            </div>
            <div>
                <label for="momo_number">Your momo Number</label>
                {{form.momo_number}}
            </div>
            <div>
                <label for="amount">Amount</label>
                {{form.amount}}
            </div>
             <div>
                <img src="{% static 'base/imgs/momo.webp' %}" alt="momo icon" style="width: 50px;aspect-ratio: 1;border-radius: 10px;">
            </div>
            <button type="submit">click to pay with momo</button>
        </form>
    </div>
</section>
{% endblock content %}

internease/base/templates/base/success.html
{% extends "main.html" %}

{% block title %}
    Successfull
{% endblock title %}

{% block content %}
    <div>
        <h2><strong>🕊Your Application Was Successfull</strong></h2>
    </div>
{% endblock content %}

internease/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'base/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/apply.css' %}">

    <title> InternEase | {% block title %}

    {% endblock title %}</title>
</head>
<body>

<header>
    {% include "navbar.html" %}
</header>
<main>
    {% block content %}
      
    {% endblock content %}
</main>
    
</body>
</html>

internease/templates/navbar.html
<section class="navbar">
    <nav>
        <h2>Izion👨🏿‍💻👩🏿‍💻</h2>
        <ul>
            <li><a href="{% url 'base:applied_interns' %}">Interns</a></li>
            <li><a href="{% url 'base:apply' %}">Apply</a></li>
            <li><a href="{% url 'base:register' %}">Register</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </nav>
</section>